package ch.uzh.ifi.attempto.aceview.model.event;

public enum EventType {
	ACTIVE_ACETEXT_CHANGED,
	ACETEXT_CREATED,
	ACETEXT_CHANGED,
	ACETEXT_LOADED,
	ACETEXT_ANSWERS_CHANGED,
	ACELEXICON_CHANGED;
}